-- Ids are UUIDv7 generated by the application; the uuidv7() default
-- (PostgreSQL 18+) only covers rows inserted by hand or by other tools.
CREATE TABLE tasks (
    id         uuid        PRIMARY KEY DEFAULT uuidv7(),
    title      text        NOT NULL CONSTRAINT tasks_title_length CHECK (char_length(title) BETWEEN 1 AND 200),
    done       boolean     NOT NULL DEFAULT false,
    version    integer     NOT NULL DEFAULT 1 CONSTRAINT tasks_version_positive CHECK (version >= 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
