// Package mysql is Forge's MySQL and MariaDB adapter: a database/sql pool
// configured for safe defaults, error translation into fault errors and
// SQL-file migrations.
//
// Every connection runs in UTC with utf8mb4 and a strict sql_mode, so invalid
// data is rejected instead of being silently truncated or zeroed, and
// statements are bounded by FORGE_DATABASE_STATEMENT_TIMEOUT: every statement
// on MariaDB, only SELECT on MySQL (bound writes there with a context
// deadline). Forge owns these session settings: the connection URL accepts
// only the tls parameter.
//
// Forge is SQL-first. Repositories hold explicit SQL (hand-written or
// generated by sqlc for database/sql, whose DBTX interface matches
// sqldb.DBTX); there is no ORM and no query builder. Store UUIDv7 identifiers
// in CHAR(36) columns: uuid.UUID reads and writes its text form, which sorts
// in generation order.
package mysql

import (
	"context"
	"database/sql"
	sqldriver "database/sql/driver"
	"errors"
	"fmt"
	"io"
	"net"
	"net/url"
	"slices"
	"strconv"
	"strings"
	"time"

	driver "github.com/go-sql-driver/mysql"

	"github.com/fabriciobonjorno/forge-go/config"
	"github.com/fabriciobonjorno/forge-go/sqldb"
)

const (
	defaultPort = "3306"

	// sqlMode makes the server reject bad data instead of truncating it,
	// storing zero dates or turning division by zero into NULL, for
	// transactional and non-transactional tables alike. ONLY_FULL_GROUP_BY
	// keeps grouped queries deterministic.
	sqlMode = "ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

	errNotConfigured = "database is not configured: set FORGE_DATABASE_URL"
	errInvalidURL    = "FORGE_DATABASE_URL must be mysql://user:password@host:port/database (percent-encode special characters in the password)"
)

// tlsModes are the accepted values of the tls URL parameter. true verifies
// the server certificate; skip-verify and preferred encrypt without
// verifying, so they can be intercepted; false disables TLS. Production
// configuration requires true (see config).
var tlsModes = map[string]bool{"true": true, "skip-verify": true, "preferred": true, "false": true}

// Open creates a connection pool from validated configuration and verifies
// connectivity within cfg.ConnectTimeout, so misconfiguration fails at
// startup rather than on the first request. It serves MySQL and MariaDB.
func Open(ctx context.Context, cfg config.Database) (*sqldb.DB, error) {
	pool, err := openPool(cfg, false)
	if err != nil {
		return nil, err
	}
	db, err := sqldb.New(pool, cfg, classify)
	if err != nil {
		_ = pool.Close()
		return nil, err
	}
	pingCtx, cancel := context.WithTimeout(ctx, cfg.ConnectTimeout)
	defer cancel()
	if err := db.Ping(pingCtx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("connect to database: %w", err)
	}
	return db, nil
}

// openPool returns a pool whose connections are configured by Forge.
// multiStatements lets one Exec carry several statements. Only the
// migrator's dedicated pool enables it: on an application pool it would turn
// any SQL injection into stacked-query injection.
func openPool(cfg config.Database, multiStatements bool) (*sql.DB, error) {
	driverConfig, err := newDriverConfig(cfg)
	if err != nil {
		return nil, err
	}
	driverConfig.MultiStatements = multiStatements
	base, err := driver.NewConnector(driverConfig)
	if err != nil {
		// Not wrapped: driver configuration errors can quote the settings.
		return nil, errors.New(errInvalidURL)
	}
	return sql.OpenDB(&connector{base: base, statementTimeout: cfg.StatementTimeout}), nil
}

// newDriverConfig builds the driver configuration field by field from the
// mysql:// URL. It never formats a DSN string, so no value in the URL can
// inject driver options.
func newDriverConfig(cfg config.Database) (*driver.Config, error) {
	if cfg.URL.IsZero() {
		return nil, errors.New(errNotConfigured)
	}
	switch adapter := cfg.Adapter(); adapter {
	case config.AdapterMySQL:
	case "":
		return nil, errors.New(errInvalidURL)
	default:
		return nil, fmt.Errorf("FORGE_DATABASE_URL selects the %s adapter, but this application uses mysql", adapter)
	}
	// Errors below are never wrapped: url errors quote the URL, password
	// included.
	parsed, err := url.Parse(cfg.URL.Reveal())
	if err != nil || parsed.Opaque != "" || parsed.Fragment != "" || parsed.User == nil || parsed.User.Username() == "" {
		return nil, errors.New(errInvalidURL)
	}
	host, port := parsed.Hostname(), parsed.Port()
	if port == "" {
		port = defaultPort
	}
	if number, err := strconv.Atoi(port); host == "" || err != nil || number < 1 || number > 65535 {
		return nil, errors.New(errInvalidURL)
	}
	database := strings.TrimPrefix(parsed.Path, "/")
	if database == "" || strings.Contains(database, "/") {
		return nil, errors.New(errInvalidURL)
	}
	tlsMode, err := parseParameters(parsed.RawQuery)
	if err != nil {
		return nil, err
	}

	password, _ := parsed.User.Password()
	driverConfig := driver.NewConfig()
	driverConfig.User = parsed.User.Username()
	driverConfig.Passwd = password
	driverConfig.Net = "tcp"
	driverConfig.Addr = net.JoinHostPort(host, port)
	driverConfig.DBName = database
	if tlsMode != "false" {
		driverConfig.TLSConfig = tlsMode
	}
	driverConfig.Timeout = cfg.ConnectTimeout
	// Times are exchanged as time.Time in UTC; the session time_zone is UTC
	// too (see sessionSetup), so TIMESTAMP and NOW() agree with Go.
	driverConfig.ParseTime = true
	driverConfig.Loc = time.UTC
	// Explicit even where they are the driver's defaults: server-side
	// prepared statements instead of client-side interpolation, no LOAD DATA
	// LOCAL INFILE, no plaintext or pre-4.1 password methods.
	driverConfig.InterpolateParams = false
	driverConfig.AllowAllFiles = false
	driverConfig.AllowCleartextPasswords = false
	driverConfig.AllowOldPasswords = false
	driverConfig.MultiStatements = false
	return driverConfig, nil
}

// parseParameters validates the URL query and returns the tls mode. Every
// other parameter is rejected: Forge sets the session (time zone, character
// set, sql_mode, timeouts) and the driver options itself, and silently
// ignoring an option such as parseTime or multiStatements would be worse.
func parseParameters(rawQuery string) (string, error) {
	values, err := url.ParseQuery(rawQuery)
	if err != nil {
		return "", errors.New(errInvalidURL)
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	for _, key := range keys {
		if key != "tls" {
			return "", fmt.Errorf("FORGE_DATABASE_URL parameter %q is not supported: Forge sets the MySQL session itself and accepts only tls", key)
		}
	}
	tls := values["tls"]
	switch {
	case len(tls) == 0:
		return "false", nil
	case len(tls) == 1 && tlsModes[tls[0]]:
		return tls[0], nil
	default:
		return "", errors.New("FORGE_DATABASE_URL parameter tls must be one of true, skip-verify, preferred or false")
	}
}

// flavor is the server family, which differs in how statements are bounded.
type flavor int

const (
	flavorMySQL flavor = iota
	flavorMariaDB
)

// detectFlavor reads VERSION(): MariaDB reports, for example,
// "11.8.2-MariaDB-ubu2404"; MySQL reports "8.4.5".
func detectFlavor(version string) flavor {
	if strings.Contains(strings.ToLower(version), "mariadb") {
		return flavorMariaDB
	}
	return flavorMySQL
}

// timeoutAssignment bounds statements for the session; zero lifts the bound.
//
// MariaDB's max_statement_time (seconds) applies to every statement. MySQL's
// max_execution_time (milliseconds) applies only to read-only SELECT
// statements: INSERT, UPDATE, DELETE and DDL are not bounded server-side on
// MySQL, so bound them with a context deadline, which closes the connection
// when it expires.
func timeoutAssignment(f flavor, timeout time.Duration) string {
	ms := max(timeout.Milliseconds(), 0)
	if f == flavorMariaDB {
		return fmt.Sprintf("max_statement_time = %d.%03d", ms/1000, ms%1000)
	}
	return "max_execution_time = " + strconv.FormatInt(ms, 10)
}

// sessionSetup is the one statement that configures each new connection.
// Every value is a constant or a number, never input.
func sessionSetup(f flavor, statementTimeout time.Duration) string {
	return "SET NAMES utf8mb4, time_zone = '+00:00', sql_mode = '" + sqlMode + "', " + timeoutAssignment(f, statementTimeout)
}

// connector configures the session of every new connection before
// database/sql can use it. The flavor is detected per connection, so the
// setup is always the one the server understands; a failure closes the
// connection and is returned, so no connection runs with default settings.
// The driver's session reset keeps session variables, so the setup lasts for
// the connection's lifetime.
type connector struct {
	base             sqldriver.Connector
	statementTimeout time.Duration
}

func (c *connector) Connect(ctx context.Context) (sqldriver.Conn, error) {
	conn, err := c.base.Connect(ctx)
	if err != nil {
		return nil, err
	}
	if err := configureSession(ctx, conn, c.statementTimeout); err != nil {
		_ = conn.Close()
		return nil, fmt.Errorf("configure database session: %w", err)
	}
	return conn, nil
}

func (c *connector) Driver() sqldriver.Driver { return c.base.Driver() }

func configureSession(ctx context.Context, conn sqldriver.Conn, statementTimeout time.Duration) error {
	queryer, canQuery := conn.(sqldriver.QueryerContext)
	execer, canExec := conn.(sqldriver.ExecerContext)
	if !canQuery || !canExec {
		return errors.New("driver connection cannot run queries")
	}
	version, err := queryVersion(ctx, queryer)
	if err != nil {
		return err
	}
	_, err = execer.ExecContext(ctx, sessionSetup(detectFlavor(version), statementTimeout), nil)
	return err
}

func queryVersion(ctx context.Context, queryer sqldriver.QueryerContext) (string, error) {
	rows, err := queryer.QueryContext(ctx, "SELECT VERSION()", nil)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()
	dest := make([]sqldriver.Value, len(rows.Columns()))
	if len(dest) != 1 {
		return "", errors.New("unexpected server version result")
	}
	if err := rows.Next(dest); err != nil {
		if errors.Is(err, io.EOF) {
			return "", errors.New("server did not report its version")
		}
		return "", err
	}
	switch version := dest[0].(type) {
	case []byte:
		return string(version), nil
	case string:
		return version, nil
	default:
		return "", errors.New("unexpected server version result")
	}
}
