// Package postgres is Forge's PostgreSQL adapter: a configured pgx connection
// pool, explicit transactions, error translation into fault errors, advisory
// locks and SQL-file migrations.
//
// Forge is SQL-first. Repositories hold explicit SQL (hand-written or
// generated by sqlc, whose pgx/v5 DBTX interface matches DBTX here); there is
// no ORM and no query builder.
package postgres

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/fabriciobonjorno/forge-go/config"
	"github.com/fabriciobonjorno/forge-go/sqldb"
)

// DBTX is satisfied by *DB and pgx.Tx, so a repository written against it runs
// both standalone and inside a transaction.
type DBTX interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// DB is a PostgreSQL connection pool.
type DB struct {
	pool *pgxpool.Pool
}

var _ DBTX = (*DB)(nil)

// Open creates a connection pool from validated configuration and verifies
// connectivity within cfg.ConnectTimeout, so misconfiguration fails at
// startup rather than on the first request.
func Open(ctx context.Context, cfg config.Database) (*DB, error) {
	poolConfig, err := parseConfig(cfg)
	if err != nil {
		return nil, err
	}
	poolConfig.MaxConns = cfg.MaxConns
	poolConfig.MinConns = cfg.MinConns
	poolConfig.MaxConnLifetime = cfg.MaxConnLifetime
	poolConfig.MaxConnIdleTime = cfg.MaxConnIdleTime
	poolConfig.ConnConfig.RuntimeParams["statement_timeout"] = strconv.FormatInt(cfg.StatementTimeout.Milliseconds(), 10)
	if poolConfig.ConnConfig.RuntimeParams["application_name"] == "" {
		poolConfig.ConnConfig.RuntimeParams["application_name"] = "forge"
	}
	// pgx scans timestamptz into time.Local by default, which makes results
	// depend on the host's zone. Forge returns instants in UTC everywhere.
	poolConfig.AfterConnect = func(_ context.Context, conn *pgx.Conn) error {
		conn.TypeMap().RegisterType(&pgtype.Type{
			Name:  "timestamptz",
			OID:   pgtype.TimestamptzOID,
			Codec: &pgtype.TimestamptzCodec{ScanLocation: time.UTC},
		})
		return nil
	}

	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		return nil, fmt.Errorf("create connection pool: %w", err)
	}
	pingCtx, cancel := context.WithTimeout(ctx, cfg.ConnectTimeout)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connect to database: %w", err)
	}
	return &DB{pool: pool}, nil
}

// parseConfig builds the pgx configuration shared by the pool and the
// migrator's dedicated session.
func parseConfig(cfg config.Database) (*pgxpool.Config, error) {
	if cfg.URL.IsZero() {
		return nil, errors.New("database is not configured: set FORGE_DATABASE_URL")
	}
	if adapter := cfg.Adapter(); adapter != config.AdapterPostgres {
		return nil, fmt.Errorf("FORGE_DATABASE_URL selects the %s adapter, but this application uses postgres", adapter)
	}
	poolConfig, err := pgxpool.ParseConfig(cfg.URL.Reveal())
	if err != nil {
		// Not wrapped: parse errors can quote the connection string.
		return nil, errors.New("FORGE_DATABASE_URL is not a valid PostgreSQL connection string")
	}
	if err := matchesValidatedURL(cfg.URL.Reveal(), poolConfig.ConnConfig.Config); err != nil {
		return nil, err
	}
	poolConfig.ConnConfig.ConnectTimeout = cfg.ConnectTimeout
	return poolConfig, nil
}

// matchesValidatedURL checks that pgx, whose libpq-style parser differs from
// net/url, will connect exactly where and how config validated: the same
// host and port, and TLS on every attempt (pgx implements sslmode=prefer and
// allow as plaintext fallbacks) whenever the URL asks for an encrypted mode.
// It is defense in depth behind config's rejection of ambiguous URLs.
func matchesValidatedURL(raw string, parsed pgconn.Config) error {
	validated, err := url.Parse(raw)
	if err != nil {
		return errors.New("FORGE_DATABASE_URL is not a valid PostgreSQL connection string")
	}
	port := uint16(5432)
	if validated.Port() != "" {
		value, err := strconv.ParseUint(validated.Port(), 10, 16)
		if err != nil {
			return errors.New("FORGE_DATABASE_URL has an invalid port")
		}
		port = uint16(value)
	}
	ambiguous := errors.New("FORGE_DATABASE_URL is ambiguous: PostgreSQL would connect differently than it was validated")
	attempts := append([]*pgconn.FallbackConfig{{Host: parsed.Host, Port: parsed.Port, TLSConfig: parsed.TLSConfig}}, parsed.Fallbacks...)
	encrypted := map[string]bool{"require": true, "verify-ca": true, "verify-full": true}[validated.Query().Get("sslmode")]
	for _, attempt := range attempts {
		if attempt.Host != validated.Hostname() || attempt.Port != port || (encrypted && attempt.TLSConfig == nil) {
			return ambiguous
		}
	}
	return nil
}

func (db *DB) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	return db.pool.Exec(ctx, sql, arguments...)
}

func (db *DB) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	return db.pool.Query(ctx, sql, args...)
}

func (db *DB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	return db.pool.QueryRow(ctx, sql, args...)
}

// Ping verifies a connection can be used. Its signature matches health.Check,
// so it can be registered directly as a readiness check.
func (db *DB) Ping(ctx context.Context) error { return db.pool.Ping(ctx) }

// Close waits for acquired connections to be released and closes the pool.
func (db *DB) Close() { db.pool.Close() }

// Shutdown closes the pool like Close but stops waiting when ctx ends, so a
// connection held by a stuck request cannot block process exit. Its signature
// matches forge.ShutdownHook: app.OnShutdown(db.Shutdown).
func (db *DB) Shutdown(ctx context.Context) error {
	return sqldb.CloseWithin(ctx, func() error { db.pool.Close(); return nil }, func() int { return int(db.pool.Stat().AcquiredConns()) })
}

// Pool exposes the underlying pgx pool for capabilities Forge does not wrap,
// such as COPY or LISTEN/NOTIFY. It is the explicit escape hatch.
func (db *DB) Pool() *pgxpool.Pool { return db.pool }
