package postgres_test

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"slices"
	"strings"
	"sync"
	"testing"
	"testing/fstest"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	forge "github.com/fabriciobonjorno/forge-go"
	"github.com/fabriciobonjorno/forge-go/config"
	"github.com/fabriciobonjorno/forge-go/fault"
	"github.com/fabriciobonjorno/forge-go/migrate"
	"github.com/fabriciobonjorno/forge-go/postgres"
	"github.com/fabriciobonjorno/forge-go/postgres/postgrestest"
	"github.com/fabriciobonjorno/forge-go/tenancy"
	"github.com/fabriciobonjorno/forge-go/uuid"
)

var discard = slog.New(slog.NewTextHandler(io.Discard, nil))

func TestUUIDv7RoundTripAndOrdering(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	ctx := context.Background()
	if _, err := db.Exec(ctx, "CREATE TABLE items (id uuid PRIMARY KEY DEFAULT uuidv7(), seq int NOT NULL)"); err != nil {
		t.Fatal(err)
	}
	var generated []uuid.UUID
	for seq := range 50 {
		id := uuid.MustNew()
		generated = append(generated, id)
		if _, err := db.Exec(ctx, "INSERT INTO items (id, seq) VALUES ($1, $2)", id, seq); err != nil {
			t.Fatal(err)
		}
	}
	rows, err := db.Query(ctx, "SELECT id FROM items ORDER BY id")
	if err != nil {
		t.Fatal(err)
	}
	stored, err := pgx.CollectRows(rows, pgx.RowTo[uuid.UUID])
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(stored, generated) {
		t.Fatal("PostgreSQL uuid ordering differs from UUIDv7 generation order")
	}

	// IDs generated by the database default scan into uuid.UUID too.
	var fromDefault uuid.UUID
	if err := db.QueryRow(ctx, "INSERT INTO items (seq) VALUES (99) RETURNING id").Scan(&fromDefault); err != nil {
		t.Fatal(err)
	}
	if fromDefault.Version() != 7 || fromDefault.Compare(generated[len(generated)-1]) <= 0 {
		t.Fatalf("database default id %s is not a later UUIDv7", fromDefault)
	}
}

func TestStatementTimeoutIsApplied(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	var timeout string
	if err := db.QueryRow(context.Background(), "SHOW statement_timeout").Scan(&timeout); err != nil {
		t.Fatal(err)
	}
	if timeout != "30s" {
		t.Fatalf("statement_timeout=%s want 30s", timeout)
	}
	err := db.InTx(context.Background(), func(tx pgx.Tx) error {
		if _, err := tx.Exec(context.Background(), "SET LOCAL statement_timeout = '20ms'"); err != nil {
			return err
		}
		_, err := tx.Exec(context.Background(), "SELECT pg_sleep(1)")
		return err
	})
	if translated := fault.From(postgres.Translate(err)); translated == nil || translated.Code != "timeout" {
		t.Fatalf("expected timeout fault, got %v", err)
	}
}

func TestInTxCommitRollbackAndPanic(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	ctx := context.Background()
	if _, err := db.Exec(ctx, "CREATE TABLE counters (name text PRIMARY KEY)"); err != nil {
		t.Fatal(err)
	}
	insert := func(name string) func(pgx.Tx) error {
		return func(tx pgx.Tx) error {
			_, err := tx.Exec(ctx, "INSERT INTO counters (name) VALUES ($1)", name)
			return err
		}
	}
	if err := db.InTx(ctx, insert("committed")); err != nil {
		t.Fatal(err)
	}
	sentinel := errors.New("business rule failed")
	if err := db.InTx(ctx, func(tx pgx.Tx) error { _ = insert("rolled-back")(tx); return sentinel }); !errors.Is(err, sentinel) {
		t.Fatalf("fn error must be returned unchanged, got %v", err)
	}
	func() {
		defer func() { _ = recover() }()
		_ = db.InTx(ctx, func(tx pgx.Tx) error { _ = insert("panicked")(tx); panic("boom") })
	}()

	rows, err := db.Query(ctx, "SELECT name FROM counters ORDER BY name")
	if err != nil {
		t.Fatal(err)
	}
	names, err := pgx.CollectRows(rows, pgx.RowTo[string])
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(names, []string{"committed"}) {
		t.Fatalf("rows=%v, want only the committed one", names)
	}
	if stat := db.Pool().Stat(); stat.AcquiredConns() != 0 {
		t.Fatalf("%d connections leaked", stat.AcquiredConns())
	}
}

func TestInTenantTxEnforcesRLSAndDoesNotLeakTenant(t *testing.T) {
	db := postgrestest.New(t)
	ctx := context.Background()
	role := "forge_rls_" + strings.ReplaceAll(uuid.MustNew().String(), "-", "")[:16]
	quotedRole := pgx.Identifier{role}.Sanitize()
	if _, err := db.Exec(ctx, "CREATE ROLE "+quotedRole+" NOLOGIN"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_, _ = db.Exec(context.Background(), "DROP OWNED BY "+quotedRole)
		_, _ = db.Exec(context.Background(), "DROP ROLE "+quotedRole)
	})
	if _, err := db.Exec(ctx, `
		CREATE TABLE tenant_documents (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, title text NOT NULL);
		ALTER TABLE tenant_documents ENABLE ROW LEVEL SECURITY;
		ALTER TABLE tenant_documents FORCE ROW LEVEL SECURITY;
		CREATE POLICY tenant_documents_isolation ON tenant_documents
			USING (tenant_id::text = current_setting('forge.tenant_id', true))
			WITH CHECK (tenant_id::text = current_setting('forge.tenant_id', true));
		GRANT SELECT, INSERT ON tenant_documents TO `+quotedRole); err != nil {
		t.Fatal(err)
	}
	tenantA, _ := tenancy.New(uuid.MustNew())
	tenantB, _ := tenancy.New(uuid.MustNew())
	if _, err := db.Exec(ctx, "INSERT INTO tenant_documents (id, tenant_id, title) VALUES ($1, $2, 'a'), ($3, $4, 'b')",
		uuid.MustNew(), tenantA.ID, uuid.MustNew(), tenantB.ID); err != nil {
		t.Fatal(err)
	}

	tenantContext := func(tenant tenancy.Tenant) context.Context {
		result, err := tenancy.WithContext(ctx, tenant)
		if err != nil {
			t.Fatal(err)
		}
		return result
	}
	assertVisible := func(tenant tenancy.Tenant, want string) {
		t.Helper()
		err := db.InTenantTx(tenantContext(tenant), func(tx pgx.Tx) error {
			if _, err := tx.Exec(ctx, "SET LOCAL ROLE "+quotedRole); err != nil {
				return err
			}
			rows, err := tx.Query(ctx, "SELECT title FROM tenant_documents ORDER BY title")
			if err != nil {
				return err
			}
			titles, err := pgx.CollectRows(rows, pgx.RowTo[string])
			if err != nil {
				return err
			}
			if !slices.Equal(titles, []string{want}) {
				return fmt.Errorf("tenant saw titles %v, want [%s]", titles, want)
			}
			if _, err := tx.Exec(ctx, "SAVEPOINT cross_tenant_insert"); err != nil {
				return fmt.Errorf("savepoint cross-tenant insert: %w", err)
			}
			other := tenantA
			if tenant == tenantA {
				other = tenantB
			}
			_, err = tx.Exec(ctx, "INSERT INTO tenant_documents (id, tenant_id, title) VALUES ($1, $2, 'cross-tenant')", uuid.MustNew(), other.ID)
			if err == nil {
				return errors.New("RLS allowed a cross-tenant insert")
			}
			var pgErr *pgconn.PgError
			if !errors.As(err, &pgErr) || pgErr.Code != "42501" {
				return fmt.Errorf("cross-tenant insert failed for an unexpected reason: %w", err)
			}
			if _, err := tx.Exec(ctx, "ROLLBACK TO SAVEPOINT cross_tenant_insert"); err != nil {
				return fmt.Errorf("rollback cross-tenant insert: %w", err)
			}
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	assertVisible(tenantA, "a")
	assertVisible(tenantB, "b")

	if err := db.InTenantTx(context.Background(), func(pgx.Tx) error { return nil }); !errors.Is(err, tenancy.ErrMissing) {
		t.Fatalf("missing tenant error=%v", err)
	}
	var leaked string
	if err := db.QueryRow(ctx, "SELECT current_setting('forge.tenant_id', true)").Scan(&leaked); err != nil {
		t.Fatal(err)
	}
	if leaked != "" {
		t.Fatalf("tenant setting leaked into pooled session: %q", leaked)
	}
}

// TestSerializableRetry forces a serialization failure: both transactions
// read the same rows before either writes, so one must abort with 40001.
func TestSerializableRetry(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	ctx := context.Background()
	if _, err := db.Exec(ctx, "CREATE TABLE doctors (name text PRIMARY KEY, on_call bool NOT NULL); INSERT INTO doctors VALUES ('a', true), ('b', true)"); err != nil {
		t.Fatal(err)
	}
	var barrier sync.WaitGroup
	barrier.Add(2)
	var attempts sync.Map
	goOffCall := func(name string, opts postgres.TxOptions) error {
		return db.InTxWith(ctx, opts, func(tx pgx.Tx) error {
			count, _ := attempts.LoadOrStore(name, new(int))
			*count.(*int)++
			var onCall int
			if err := tx.QueryRow(ctx, "SELECT count(*) FROM doctors WHERE on_call").Scan(&onCall); err != nil {
				return err
			}
			if *count.(*int) == 1 {
				barrier.Done()
				barrier.Wait() // both have read before either writes
			}
			if onCall < 2 {
				return nil // someone must stay on call
			}
			_, err := tx.Exec(ctx, "UPDATE doctors SET on_call = false WHERE name = $1", name)
			return err
		})
	}
	opts := postgres.TxOptions{Isolation: postgres.Serializable, Attempts: 5}
	errs := make(chan error, 2)
	for _, name := range []string{"a", "b"} {
		go func() { errs <- goOffCall(name, opts) }()
	}
	for range 2 {
		if err := <-errs; err != nil {
			t.Fatalf("retry did not resolve the serialization failure: %v", err)
		}
	}
	var onCall int
	if err := db.QueryRow(ctx, "SELECT count(*) FROM doctors WHERE on_call").Scan(&onCall); err != nil {
		t.Fatal(err)
	}
	if onCall != 1 {
		t.Fatalf("on_call=%d: serializable invariant violated", onCall)
	}
	retried := 0
	attempts.Range(func(_, count any) bool { retried += *count.(*int) - 1; return true })
	if retried == 0 {
		t.Fatal("expected at least one retry")
	}
}

func TestTranslateAgainstRealConstraints(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	ctx := context.Background()
	if _, err := db.Exec(ctx, `
		CREATE TABLE projects (id uuid PRIMARY KEY);
		CREATE TABLE tasks (
			id uuid PRIMARY KEY,
			project_id uuid REFERENCES projects (id),
			title text NOT NULL CONSTRAINT tasks_title_length CHECK (length(title) <= 5),
			CONSTRAINT tasks_title_key UNIQUE (title)
		)`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(ctx, "INSERT INTO tasks (id, title) VALUES ($1, 'a')", uuid.MustNew()); err != nil {
		t.Fatal(err)
	}
	cases := []struct {
		name, sql string
		args      []any
		wantCode  string
	}{
		{"unique", "INSERT INTO tasks (id, title) VALUES ($1, 'a')", []any{uuid.MustNew()}, "already_exists"},
		{"foreign key", "INSERT INTO tasks (id, project_id, title) VALUES ($1, $2, 'b')", []any{uuid.MustNew(), uuid.MustNew()}, "reference_violation"},
		{"check", "INSERT INTO tasks (id, title) VALUES ($1, 'too long')", []any{uuid.MustNew()}, "constraint_violation"},
		{"not null", "INSERT INTO tasks (id, title) VALUES ($1, NULL)", []any{uuid.MustNew()}, "internal_error"},
	}
	for _, test := range cases {
		_, err := db.Exec(ctx, test.sql, test.args...)
		if translated := fault.From(postgres.Translate(err)); translated == nil || translated.Code != test.wantCode {
			t.Errorf("%s: got %v", test.name, err)
		}
	}
	var missing uuid.UUID
	err := db.QueryRow(ctx, "SELECT id FROM tasks WHERE title = 'none'").Scan(&missing)
	if translated := fault.From(postgres.Translate(err)); translated == nil || translated.Status() != http.StatusNotFound {
		t.Errorf("no rows: got %v", err)
	}
}

func TestAdvisoryXactLock(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	ctx := context.Background()
	key := postgres.LockKey("test:advisory")
	held := make(chan struct{})
	release := make(chan struct{})
	done := make(chan error, 1)
	go func() {
		done <- db.InTx(ctx, func(tx pgx.Tx) error {
			if err := postgres.AdvisoryXactLock(ctx, tx, key); err != nil {
				return err
			}
			close(held)
			<-release
			return nil
		})
	}()
	<-held
	err := db.InTx(ctx, func(tx pgx.Tx) error {
		acquired, err := postgres.TryAdvisoryXactLock(ctx, tx, key)
		if err == nil && acquired {
			return errors.New("lock acquired while another transaction holds it")
		}
		return err
	})
	if err != nil {
		t.Fatal(err)
	}
	close(release)
	if err := <-done; err != nil {
		t.Fatal(err)
	}
	err = db.InTx(ctx, func(tx pgx.Tx) error {
		acquired, err := postgres.TryAdvisoryXactLock(ctx, tx, key)
		if err == nil && !acquired {
			return errors.New("lock not released at commit")
		}
		return err
	})
	if err != nil {
		t.Fatal(err)
	}
}

func migrationFS() fstest.MapFS {
	return fstest.MapFS{
		"20260101000000_create_accounts.up.sql": {Data: []byte(`
			CREATE TABLE accounts (id uuid PRIMARY KEY DEFAULT uuidv7(), email text NOT NULL);
			CREATE UNIQUE INDEX accounts_email_key ON accounts (lower(email));`)},
		"20260101000000_create_accounts.down.sql": {Data: []byte("DROP TABLE accounts;")},
		"20260102000000_index_accounts.up.sql":    {Data: []byte("-- forge:no-transaction\nCREATE INDEX CONCURRENTLY accounts_id_idx ON accounts (id);")},
		"20260102000000_index_accounts.down.sql":  {Data: []byte("-- forge:no-transaction\nDROP INDEX CONCURRENTLY accounts_id_idx;")},
	}
}

func newMigrator(t *testing.T, cfg config.Database, fsys fstest.MapFS) *migrate.Migrator {
	t.Helper()
	migrations, err := migrate.LoadMigrations(fsys)
	if err != nil {
		t.Fatal(err)
	}
	migrator, err := postgres.NewMigrator(cfg, migrations, discard)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = migrator.Close() })
	return migrator
}

func TestMigratorLifecycle(t *testing.T) {
	t.Parallel()
	db, cfg := postgrestest.NewWithConfig(t)
	ctx := context.Background()
	migrator := newMigrator(t, cfg, migrationFS())

	applied, err := migrator.Up(ctx)
	if err != nil || len(applied) != 2 {
		t.Fatalf("applied=%d err=%v", len(applied), err)
	}
	if again, err := migrator.Up(ctx); err != nil || len(again) != 0 {
		t.Fatalf("second Up must be a no-op: applied=%d err=%v", len(again), err)
	}
	statuses, err := migrator.Status(ctx)
	if err != nil || len(statuses) != 2 || statuses[0].State != migrate.StateApplied || statuses[1].AppliedAt.IsZero() {
		t.Fatalf("statuses=%+v err=%v", statuses, err)
	}

	reverted, err := migrator.Down(ctx, 2)
	if err != nil || len(reverted) != 2 || reverted[0].Name != "index_accounts" {
		t.Fatalf("reverted=%+v err=%v", reverted, err)
	}
	var exists bool
	if err := db.QueryRow(ctx, "SELECT to_regclass('accounts') IS NOT NULL").Scan(&exists); err != nil || exists {
		t.Fatalf("accounts still exists after rollback (err=%v)", err)
	}
}

func TestMigratorFailsClosed(t *testing.T) {
	t.Parallel()
	ctx := context.Background()

	t.Run("failed migration leaves no trace", func(t *testing.T) {
		t.Parallel()
		db, cfg := postgrestest.NewWithConfig(t)
		broken := fstest.MapFS{"20260101000000_broken.up.sql": {Data: []byte("CREATE TABLE half_done (id int); SELECT * FROM missing_table;")}}
		if _, err := newMigrator(t, cfg, broken).Up(ctx); err == nil {
			t.Fatal("expected failure")
		}
		var tableExists, recorded bool
		if err := db.QueryRow(ctx, "SELECT to_regclass('half_done') IS NOT NULL, EXISTS (SELECT 1 FROM forge_schema_migrations)").Scan(&tableExists, &recorded); err != nil {
			t.Fatal(err)
		}
		if tableExists || recorded {
			t.Fatalf("partial migration persisted: table=%v recorded=%v", tableExists, recorded)
		}
	})

	t.Run("modified migration", func(t *testing.T) {
		t.Parallel()
		_, cfg := postgrestest.NewWithConfig(t)
		if _, err := newMigrator(t, cfg, migrationFS()).Up(ctx); err != nil {
			t.Fatal(err)
		}
		edited := migrationFS()
		edited["20260101000000_create_accounts.up.sql"] = &fstest.MapFile{Data: []byte("CREATE TABLE accounts (id uuid);")}
		if _, err := newMigrator(t, cfg, edited).Up(ctx); err == nil || !strings.Contains(err.Error(), "modified") {
			t.Fatalf("expected modified-migration error, got %v", err)
		}
	})

	t.Run("database ahead of build", func(t *testing.T) {
		t.Parallel()
		_, cfg := postgrestest.NewWithConfig(t)
		if _, err := newMigrator(t, cfg, migrationFS()).Up(ctx); err != nil {
			t.Fatal(err)
		}
		older := migrationFS()
		delete(older, "20260102000000_index_accounts.up.sql")
		delete(older, "20260102000000_index_accounts.down.sql")
		if _, err := newMigrator(t, cfg, older).Up(ctx); err == nil || !strings.Contains(err.Error(), "does not contain") {
			t.Fatalf("expected unknown-migration error, got %v", err)
		}
	})

	t.Run("irreversible rollback reverts nothing", func(t *testing.T) {
		t.Parallel()
		_, cfg := postgrestest.NewWithConfig(t)
		fsys := migrationFS()
		delete(fsys, "20260102000000_index_accounts.down.sql")
		migrator := newMigrator(t, cfg, fsys)
		if _, err := migrator.Up(ctx); err != nil {
			t.Fatal(err)
		}
		if _, err := migrator.Down(ctx, 2); err == nil || !strings.Contains(err.Error(), "irreversible") {
			t.Fatalf("expected irreversible error, got %v", err)
		}
		statuses, err := migrator.Status(ctx)
		if err != nil || statuses[0].State != migrate.StateApplied || statuses[1].State != migrate.StateApplied {
			t.Fatalf("rollback was partially applied: %+v err=%v", statuses, err)
		}
	})
}

func TestConcurrentMigratorsApplyOnce(t *testing.T) {
	t.Parallel()
	_, cfg := postgrestest.NewWithConfig(t)
	var total sync.WaitGroup
	results := make(chan int, 5)
	for range 5 {
		total.Go(func() {
			applied, err := newMigrator(t, cfg, migrationFS()).Up(context.Background())
			if err != nil {
				t.Error(err)
			}
			results <- len(applied)
		})
	}
	total.Wait()
	close(results)
	sum := 0
	for count := range results {
		sum += count
	}
	if sum != 2 {
		t.Fatalf("migrations applied %d times across replicas, want exactly 2", sum)
	}
}

func TestCommandsThroughApplicationBinary(t *testing.T) {
	t.Parallel()
	cfg := postgrestest.Config(t)
	lookup := func(key string) (string, bool) {
		switch key {
		case "FORGE_ENV":
			return "test", true
		case "FORGE_DATABASE_URL":
			return cfg.URL.Reveal(), true
		}
		return "", false
	}
	noop := func(context.Context, *forge.App) error { return nil }
	commands := postgres.Commands(migrationFS())
	run := func(args ...string) string {
		t.Helper()
		var stdout, stderr bytes.Buffer
		if code := forge.Execute(context.Background(), args, lookup, &stdout, &stderr, noop, commands...); code != 0 {
			t.Fatalf("%v: code=%d stderr=%s", args, code, stderr.String())
		}
		return stdout.String()
	}
	if output := run("migrate"); !strings.Contains(output, "applied  20260102000000_index_accounts") {
		t.Fatalf("migrate output: %s", output)
	}
	if output := run("migrate"); !strings.Contains(output, "up to date") {
		t.Fatalf("second migrate output: %s", output)
	}
	if output := run("migrate", "status"); strings.Count(output, "applied") != 2 {
		t.Fatalf("status output: %s", output)
	}
	if output := run("rollback"); !strings.Contains(output, "reverted 20260102000000_index_accounts") {
		t.Fatalf("rollback output: %s", output)
	}
	if output := run("migrate", "status"); !strings.Contains(output, "pending") {
		t.Fatalf("status after rollback: %s", output)
	}
}

func TestTimestampsScanInUTC(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	var scanned time.Time
	if err := db.QueryRow(context.Background(), "SELECT '2026-09-26 12:00:00-03'::timestamptz").Scan(&scanned); err != nil {
		t.Fatal(err)
	}
	if scanned.Location() != time.UTC || scanned.Hour() != 15 {
		t.Fatalf("scanned %v in %v, want 15:00 UTC", scanned, scanned.Location())
	}
}

func TestRollbackRevertsMostRecentlyAppliedAndStatusIsReadOnly(t *testing.T) {
	t.Parallel()
	db, cfg := postgrestest.NewWithConfig(t)
	ctx := context.Background()
	newer := fstest.MapFS{
		"20260105000000_newer.up.sql":   {Data: []byte("CREATE TABLE newer (id int);")},
		"20260105000000_newer.down.sql": {Data: []byte("DROP TABLE newer;")},
	}
	statuses, err := newMigrator(t, cfg, newer).Status(ctx)
	if err != nil || len(statuses) != 1 || statuses[0].State != migrate.StatePending {
		t.Fatalf("status on a never-migrated database: %+v err=%v", statuses, err)
	}
	var tracked bool
	if err := db.QueryRow(ctx, "SELECT to_regclass('forge_schema_migrations') IS NOT NULL").Scan(&tracked); err != nil || tracked {
		t.Fatalf("Status created the migrations table (err=%v)", err)
	}
	if _, err := newMigrator(t, cfg, newer).Up(ctx); err != nil {
		t.Fatal(err)
	}
	// An older version from another branch lands later: out of order.
	both := fstest.MapFS{
		"20260101000000_older.up.sql":   {Data: []byte("CREATE TABLE older (id int);")},
		"20260101000000_older.down.sql": {Data: []byte("DROP TABLE older;")},
	}
	for name, file := range newer {
		both[name] = file
	}
	migrator := newMigrator(t, cfg, both)
	if _, err := migrator.Up(ctx); err != nil {
		t.Fatal(err)
	}
	reverted, err := migrator.Down(ctx, 1)
	if err != nil || len(reverted) != 1 || reverted[0].Name != "older" {
		t.Fatalf("rollback must revert the most recently applied migration (older), got %+v err=%v", reverted, err)
	}
}

func TestShutdownStopsWaitingForHeldConnections(t *testing.T) {
	t.Parallel()
	db := postgrestest.New(t)
	held, err := db.Pool().Acquire(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer held.Release()
	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()
	started := time.Now()
	if err := db.Shutdown(ctx); err == nil || !strings.Contains(err.Error(), "1 connections still in use") {
		t.Fatalf("expected a deadline error naming the held connection, got %v", err)
	}
	if elapsed := time.Since(started); elapsed > time.Second {
		t.Fatalf("Shutdown blocked for %v", elapsed)
	}
}

func TestMigratorRejectsForeignBookkeepingLayout(t *testing.T) {
	t.Parallel()
	db, cfg := postgrestest.NewWithConfig(t)
	// The layout of a Forge pre-release: applied_at was a timestamp.
	if _, err := db.Exec(context.Background(), `CREATE TABLE forge_schema_migrations (
		version bigint PRIMARY KEY, name text NOT NULL, checksum text NOT NULL, applied_at timestamptz NOT NULL DEFAULT now());
		INSERT INTO forge_schema_migrations (version, name, checksum) VALUES (20260101000000, 'create_accounts', 'x')`); err != nil {
		t.Fatal(err)
	}
	_, err := newMigrator(t, cfg, migrationFS()).Up(context.Background())
	if err == nil || !strings.Contains(err.Error(), "does not have the expected layout") {
		t.Fatalf("expected a clear layout error, got %v", err)
	}
}

// TestMigrationCannotRedirectBookkeeping is a regression test: a migration
// that changed search_path made the unqualified bookkeeping statements target
// another schema.
func TestMigrationCannotRedirectBookkeeping(t *testing.T) {
	t.Parallel()
	_, cfg := postgrestest.NewWithConfig(t)
	fsys := fstest.MapFS{"20260101000000_switch.up.sql": {Data: []byte("CREATE SCHEMA other; SET search_path = other; CREATE TABLE t (id int);")}}
	_, err := newMigrator(t, cfg, fsys).Up(context.Background())
	if err == nil || !strings.Contains(err.Error(), "switched the session") {
		t.Fatalf("expected the session switch to be refused, got %v", err)
	}
}
